"""Reusable document generation for Markdown, HTML, and Mermaid."""

from .document import (
    BlockQuote,
    Blockquote,
    Bold,
    CodeBlock,
    Diagram,
    Document,
    Emphasis,
    Heading,
    HorizontalRule,
    Image,
    ImageBlock,
    InlineCode,
    Link,
    List,
    ListBlock,
    ListItem,
    Mermaid,
    MermaidBlock,
    OrderedList,
    Paragraph,
    RawContent,
    Report,
    ReportElement,
    ReportMetadata,
    Section,
    Strong,
    Table,
    Text,
    UnorderedList,
)
from .renderers import (
    HTMLRenderer,
    HtmlRenderer,
    MarkdownRenderer,
    escape_html,
    escape_markdown,
    render_to_string,
    write_report,
)
from .mermaid import (
    ClassDefinition,
    ClassDiagram,
    Direction,
    ER,
    ERDiagram,
    ERRelationship,
    Edge,
    FlowChart,
    Flowchart,
    MermaidDiagram,
    MermaidRenderer,
    Node,
    PieChart,
    SequenceDiagram,
    SequenceMessage,
    StateDiagram,
    StateTransition,
    Subgraph,
)

__all__ = [
    "Report", "Document", "ReportMetadata", "ReportElement",
    "Heading", "Paragraph", "Text", "Emphasis", "Bold", "Strong",
    "Link", "Image", "ImageBlock", "InlineCode", "CodeBlock",
    "ListItem", "ListBlock", "List", "UnorderedList", "OrderedList",
    "BlockQuote", "Blockquote", "Table", "HorizontalRule",
    "MermaidBlock", "Mermaid", "RawContent",
    "Diagram", "Section",
    "MarkdownRenderer", "HtmlRenderer", "HTMLRenderer",
    "escape_markdown", "escape_html",
    "render_to_string", "write_report",
    "MermaidDiagram", "Direction", "Node", "Edge", "Subgraph",
    "MermaidRenderer",
    "Flowchart", "FlowChart", "SequenceDiagram", "SequenceMessage",
    "ClassDiagram", "ClassDefinition", "StateDiagram", "StateTransition",
    "ERDiagram", "ER", "ERRelationship", "PieChart",
]
